// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjeTask.Data;

namespace ProjeTask.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjeTask.Models.BankaHesap", b =>
                {
                    b.Property<int>("BankaHesapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("DolarHesap")
                        .HasColumnType("bigint");

                    b.Property<long>("EuroHesap")
                        .HasColumnType("bigint");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<long>("SterlinHesap")
                        .HasColumnType("bigint");

                    b.HasKey("BankaHesapId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("BankaHesaplari");
                });

            modelBuilder.Entity("ProjeTask.Models.Fiyat", b =>
                {
                    b.Property<int>("FiyatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Dolar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Euro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sterlin")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FiyatId");

                    b.ToTable("Fiyatlar");
                });

            modelBuilder.Entity("ProjeTask.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ProjeTask.Models.BankaHesap", b =>
                {
                    b.HasOne("ProjeTask.Models.Kullanici", "Kullanici")
                        .WithMany("BankaHesap")
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ProjeTask.Models.Kullanici", b =>
                {
                    b.Navigation("BankaHesap");
                });
#pragma warning restore 612, 618
        }
    }
}
